version: '3.9'
services:
  app:
    container_name: eng-soft-tmdb-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    expose:
      - "8080"
    command: /bin/bash -c "while ! nc -z db 3306; do sleep 1; done; mvn spring-boot:run"
    depends_on:
      - db
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://db:3306/themoviedb?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC&autoReconnect=true&useSSL=false",
        "spring.datasource.username": "docker",
        "spring.datasource.password": "docker",
        "spring.jpa.hibernate.ddl-auto": "update",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.show-sql": "false"
      }'
    networks:
      - eng-soft-tmdb-network
  db:
    container_name: eng-soft-tmdb-mysql
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password  # Don't use in production
    restart: always
    environment:
      TZ: UTC
      MYSQL_DATABASE: themoviedb
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3306
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - eng-soft-tmdb-mysql-volume:/var/lib/mysql
    networks:
      - eng-soft-tmdb-network
volumes:
  eng-soft-tmdb-mysql-volume:
networks:
  eng-soft-tmdb-network:
    driver: bridge