#file: noinspection SpellCheckingInspection

cors:
  originPatterns: http://localhost:3000,http://localhost:4200,http://localhost:8080
spring:
  application:
    name: eng-soft-tmdb
  datasource:
    url: jdbc:mysql://localhost:3306/themoviedb?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC&autoReconnect=true&useSSL=false
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      show-sql: false
  flyway:
    enabled: false
server:
  port: 8080
#  servlet:
#    context-path: /api